on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'portfolio-frontend/**'   
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Run your project's build step
      - name: Build
        run: cd portfolio-frontend && yarn && yarn build
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages publish --project-name=daniel-wilder-dev portfolio-frontend/dist
          postCommands: rm -rf portfolio-frontend/dist
